= U of C Solar Car Telemetry Recruit Training

In order to work on the telemetry recruit training, you will need to install Angular CLI and a text editor such as Sublime.
Refer to `web-app` and `server` in `Epsilon-Telemetry-server` on github. 
You can view the current telemetry web page at `138.197.206.227`.
Sublime can be downloaded from https://www.sublimetext.com/.

== Running the project

=== Via Command Line

To run this project locally, navigate to the source directory and run the following command:

[source,bash]
----
ng serve
----

Navigate to `http://localhost:4200/`. The app will automatically reload if you change any of the source files.

== Objective

This project will give recruits a introduction to how the telemetry server works.
By completing this training, recruits can develop some skills that are required to work on the server.

== Tasks to Complete

=== Create a MPPT tab and component

 *  Run `ng generate component mppt` in the command line to generate a new mppt component within the tabs folder.
 *  Create a tab for the mppt component.
 *  The MPPT tab must display 2 sections named Unit 0 and Unit 1 containing 2 sub-sections each, Channel 0 and Channel 1.
 In each channel, the data for the heartbeat status, Array Voltage, Array Current, Battery Voltage, and Temperature must be displayed.
 The heartbeat status is shown using a circle similar to the Alive status in the battery component.
 All the other data is shown as numbers.

=== Change the stylistic elements of the webpage 

 *  You can do this in many different ways such as changing the layout, colour scheme, fonts, etc. for both the battery and MPPT tabs. 
