= U of C Solar Car Advanced Recruit Training

Intro project to learn C++ and QT

== Running the project

=== Via Command Line

To build this project on Linux navigate to the source directory and run the following commands:

[source,bash]
----
qmake
make
./batteryLife -f myData.csv -i 50
----

Refer to help for further instructions on how to add arguments to the program.
 
You can change the command line arguments within QT Creator with Projects -> Run -> Command Line Arguments.

=== Via QT Creator

In QT Creator, the above `qmake` and `make` are located in `Build`, and the project can be run through the play button. 
You'll have to set the appropriate command line arguments in `Projects > Build & Run > Run`. 

== Objective

The goal of this project is to give new recruits a good starting point to learn the required skills to work on the other projects. 
If you ever need any help with how to use Qt's functions, a good start would be to look at http://doc.qt.io/qt-5.6/reference-overview.html[Qt's reference manual]. 
Another useful resource can be found at https://doc.qt.io/qt-5/qtcore-module.html#namespaces. 
This lists and explains how to implement Qt core C++ classes, some of which (i.e. QTime) will need to be used to complete the training tasks. 
Refer to the development resources folder for the style guide. 
In this document you can find the stylistic conventions that are to be used throughout the program.

=== Tasks to Complete

 *  Implement the functions of BatteryStateOfChargeService. 
The instructions for how to calculate the required values can be found in the values and calculations section below.
 *  In order to print newly calculated values, the variables must be updated. 
There are many different ways to do this. 
This should be implemented within the addData function which can be found in BatteryStateOfChargeService.

=== Values and Calculations to Note for BatteryStateOfChargeService

 *  Refer to `BatteryStateOfChargeService.h` for the function descriptions.
 *  The time until the battery is charged can be calculated by dividing the amphours used (Ah) by the current (A). 
    The time until depletion can be calculated by dividing the remaining amphours (Ah) by the current.

=== Extra Information to Help with Task Completion

 *  Within the namespace, define any variables or formats that will be used multiple times in the program (i.e. The format of each line in batData.csv).
 *  Remember to include the header files in the corresponding cpp files as well as include Qt classes that have been implemented in the program (i.e. `#include <QTime>`).
